name: birthday
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0  # تم تحديد SDK 3.6.0 وهذا يدعم Null Safety

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.1
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_app_badger: ^1.2.0
  intl: ^0.18.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1    # اختر النسخة الأخيرة من pub.dev
  cloud_firestore: ^5.5.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # الحزمة تدعم Null Safety

flutter:
  uses-material-design: true

  assets:
    - assets/balloons_image.png
    - assets/birthdaycake.png
    - assets/music.png
    - assets/food.png
    - assets/decor.png
    - assets/guests.png
    - assets/plus.png
    - assets/firstpage.png
    - assets/secondpage.png
    - assets/music_icon.png
    - assets/sounds/Happy_Birthday_Song.mp3
    - assets/play_icon.png
    - assets/stop_icon.png
    - assets/app_icon.png

  fonts:
    - family: PlaywriteAUS
      fonts:
        - asset: fonts/PlaywriteAUSA-VariableFont_wght.ttf
