name: birthday
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0  # تم تحديد SDK 3.6.0 وهذا يدعم Null Safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^0.20.1  # الحزمة تدعم Null Safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # الحزمة تدعم Null Safety

flutter:
  assets:
    - assets/balloons_image.png
    - assets/birthdaycake.png
   
  
  fonts:
    - family: PlaywriteAUS
      fonts:
        - asset: fonts/PlaywriteAUSA-VariableFont_wght.ttf
